### ISSUE TITLE
Icons showing as squares/boxes

### ISSUE THREAD

**Issue by ghost** [joaoferreira/fabricMenuIcons#1]
Hello - I successfully uploaded the wsp file to my SharePoint Online site but all of the icons are showing as boxes/squares.

Thank you,
Ashley

**Comment by joaoferreira** [comment]
Hi Ashley, 

By default the solution get the fonts from Microsoft servers, if for some reason your connection is blocking the external request you can modify the css to load the local fonts that are deployed with the solution following the steps below:

1 - Open the site using SharePoint Designer 
2 - Go to All Files -> Style Library -> fabricMenuIcons -> css
3 - Check out and edit the **fabricMenuIcons.css** in advanced mode 
4 - Comment the first **@font-face** and uncomment the second one 
5 - Save the file, check it in and publish the major version 
6 - Refresh your browser using CTRL + F5 

If the issue persists please let me know what browser are you using
